config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create' #loginto
  delete 'sessions/destroy'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,length: {maximum: 15}
  VALID_EMAIL_REGEX = /[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/
  validates :email, presence: true,
          format: { with: VALID_EMAIL_REGEX },
          uniqueness: true
  validates :password, presence: true,length: {minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    log_in user
    redirect_to helpers_sessions_path, notice:'Successfuly logged in'
    else
    flash.now[:danger] = 'Invalid login information'
    redirect_to root_path
    end
  end

  def destroy
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id:session[user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      redirect_to root_path, flash: {success: "Your account is successfuly created"}
    else
      flash.now[:alert] = "Account creation failed"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    #params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class = "navbar navbar-default">
  <div class = "container">
    <h1 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appmatching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role='alert'><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです<h1>
  

app/views/pages/index.html.erb
<div class="top-hero-text-center">
  <div class="top-hero-text-container">
    <h1 class= "text-black">このアプリは外国人労働者向けの日本でのお仕事専用マッチングアプリです</h1>
    <h1 class= "text-black">This is a service that helps matching foreignworkers and Japanese company</h1>
    <div class= "row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', new_user_path %>
      </div>
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Log in', sessions_new_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="top-hero-text-center">
<div class= "users-new-wrapper">
  <div class= "container">
    <div class= "row">
      <div class= "col-md-offset-4 col-md-4 users-new-container">
        <h1 class= "top-hero-text-center　text-white"> Sign in </h1>
        <%= form_with model: @user do |f| %>
          <div class= "form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class= "form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class= "form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class= "form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
            <%= f.submit "Create my Account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>